### ISSUE TITLE
Attaching media to posts

### ISSUE THREAD

**Issue by StandingPadAnimations** [terhechte/Ebou#14]
Ebou can send text for posts, but would be nice if we could attach media to posts as well with Ebou.

**Comment by terhechte** [comment]
Hey, on macOS it works by drag and dropping media onto the post window. Ebou used to have a button to attach media, but I had to remove it because it would crash on older macOS versions. I'll look into enabling the button again for windows and linux.

**Comment by terhechte** [comment]
I've implemented it here :) 

https://github.com/terhechte/Ebou/pull/15
