### ISSUE TITLE
Linux build dependencies

### ISSUE THREAD

**Issue by DocKDE** [terhechte/Ebou#21]
Just a comment on the build dependencies. I used a docker container to build the app on Ubuntu successfully but I noticed that `gcc` is missing from the listed dependencies to install. For a full install of Ubuntu/Debian this won't matter as it will be available by default but in a container it isn't.

Furthermore, current Fedora doesn't have a `xdotool-devel` package. I tried compiling without it but the build failed (not sure if for this reason, though). Side note: `gcc` is also needed as a dependency here, although the build ultimately failed.

**Comment by terhechte** [comment]
Thanks! Could you share your container config, then I can add it to the repo for others to use.

For Fedora I'd hope that whoever gets it to run opens a PR with the right incantations to get it to work :)

**Comment by itsjunetime** [comment]
I got this to run on fedora - `libxdo-devel` should be available via the system repo, and installing that got it all to build for me. I'll try to file a PR for this soon, including all the packages I had to install.
