### ISSUE TITLE
Ebou adds a trailing slash to the base API URL

### ISSUE THREAD

**Issue by aumetra** [terhechte/Ebou#7]
When sending API requests, Ebou appends a trailing slash to the base API URL.  
This might work fine with Mastodon (since Rails probably just ignores that slash when routing), but alternative implementations refuse to route these URLs.

This happens because of this line:

https://github.com/terhechte/Ebou/blob/d88e3a36b8ae07fb42157d09bd1163b7d7b4b282/src/components/login/reducer.rs#L88

## Proposal

Instead of re-encoding the parsed URL as a string, re-use the `term` variable as the value since it's guaranteed to be a valid URL.

Like so:

```rust
if url::Url::parse(&term).is_ok() {
  state.selected_instance_url = Some(term);
}
```

**Comment by terhechte** [comment]
Thanks! I wasn't aware of this, will change it.

**Comment by terhechte** [comment]
@aumetra Here's the PR if you want to have a look:

https://github.com/terhechte/Ebou/pull/9
